import type { Category, HomeSlide, ProductWithCategory } from "@/lib/types";

export const categories: Category[] = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    name: "Industrial Machinery",
    slug: "industrial-machinery",
    description: "Industrial and commercial machines for production, preparation, and daily business operations.",
    image_url: null,
    sort_order: 1,
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    name: "Food Processing Equipment",
    slug: "food-processing-equipment",
    description: "Commercial food and beverage equipment for cafes, restaurants, and processing lines.",
    image_url: null,
    sort_order: 2,
  },
  {
    id: "33333333-3333-3333-3333-333333333333",
    name: "Medical Supplies & Reagents",
    slug: "medical-supplies-reagents",
    description: "Selected medical supplies, reagents, and healthcare essentials for professional use.",
    image_url: null,
    sort_order: 3,
  },
  {
    id: "44444444-4444-4444-4444-444444444444",
    name: "Printing Supplies",
    slug: "printing-supplies",
    description: "Printer ink, printer heads, and industrial printing supplies.",
    image_url: null,
    sort_order: 4,
  },
  {
    id: "55555555-5555-5555-5555-555555555555",
    name: "Fashion",
    slug: "fashion",
    description: "Everyday apparel, accessories, and textile items for wholesale or retail sourcing.",
    image_url: null,
    sort_order: 5,
  },
  {
    id: "66666666-6666-6666-6666-666666666666",
    name: "Home Textiles",
    slug: "home-textiles",
    description: "Comfortable home textile collections including bedsheets and traditional essentials.",
    image_url: null,
    sort_order: 6,
  },
  {
    id: "77777777-7777-7777-7777-777777777777",
    name: "Home Appliances",
    slug: "home-appliances",
    description: "Reliable home and kitchen appliances for daily household needs.",
    image_url: null,
    sort_order: 7,
  },
  {
    id: "88888888-8888-8888-8888-888888888888",
    name: "Kitchen Accessories",
    slug: "kitchen-accessories",
    description: "Cooking tools, kitchen gadgets, and dining accessories for modern homes and businesses.",
    image_url: null,
    sort_order: 8,
  },
  {
    id: "99999999-9999-9999-9999-999999999999",
    name: "Gadgets & Electronics",
    slug: "gadgets-electronics",
    description: "Mobile accessories, smart gadgets, and practical electronic accessories.",
    image_url: null,
    sort_order: 9,
  },
  {
    id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    name: "Kids Corner",
    slug: "kids-corner",
    description: "Children's clothing, toys, learning products, and baby essentials.",
    image_url: null,
    sort_order: 10,
  },
  {
    id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    name: "Gift Corner",
    slug: "gift-corner",
    description: "Corporate, personalized, and special occasion gifts for every memorable moment.",
    image_url: null,
    sort_order: 11,
  },
];

const productRows = [
  ["food-processing-equipment", "Premium Ice Cube Making Machine", "premium-ice-cube-making-machine", "Commercial ice cube maker for cafes, restaurants, juice bars, and event service counters.", "/images/products/1781265527362.jpeg"],
  ["food-processing-equipment", "Soft Serve Ice Cream Machine", "soft-serve-ice-cream-machine", "Countertop soft serve ice cream machine for dessert shops, kiosks, and food courts.", "/images/products/1781025892905.jpeg"],
  ["food-processing-equipment", "Premium Ice Cream Machine", "premium-ice-cream-machine", "High-output ice cream machine for smooth cones, sundaes, and dessert counter operations.", "/images/products/1781621990654.jpeg"],
  ["food-processing-equipment", "Juice Making Machine", "juice-making-machine", "Commercial juice making machine for fresh beverage preparation in shops and restaurants.", "/images/products/1782058139505.jpeg"],
  ["food-processing-equipment", "Commercial Pressure Fryer", "commercial-pressure-fryer", "Stainless steel pressure fryer for fast, juicy, and consistent fried chicken production.", "/images/products/1781508580490.jpeg"],
  ["industrial-machinery", "Professional Feed Pellet Mill", "professional-feed-pellet-mill", "Efficient feed pellet mill for poultry, fish, and animal feed production.", "/images/products/1781407405982.jpeg"],
  ["industrial-machinery", "Animal Feed Pellet Machine", "animal-feed-pellet-machine", "Compact feed pellet machinery package for small manufacturing and farm operations.", "/images/products/1781713101296.jpeg"],
  ["printing-supplies", "Kexin Premium Cutting Wheels", "kexin-premium-cutting-wheels", "Durable resin cutting wheels for metal work, fabrication, and workshop supply.", "/images/products/1781457361815.jpeg"],
  ["fashion", "Li-Ning Feidian 3 Challenger Shoes", "li-ning-feidian-3-challenger-shoes", "Lightweight performance running shoes with breathable support for daily training.", "/images/products/1781368026884.jpeg"],
  ["fashion", "Premium Sports Shoes", "premium-sports-shoes", "Comfort-focused sports shoes designed for active use, walking, and casual wear.", "/images/products/1781689912099.jpeg"],
  ["fashion", "Selector Premium Shaving Set", "selector-premium-shaving-set", "Structured grooming and shaving kit for a clean, elevated personal care routine.", "/images/products/1783082330465.jpeg"],
  ["home-textiles", "Traditional Lungi Collection", "traditional-lungi-collection", "Comfortable traditional lungi options for daily wear and retail textile sourcing.", "/images/products/1781530716533.jpeg"],
  ["home-textiles", "CYNOVIA Textile Collection", "cynovia-textile-collection", "Colorful textile collection focused on comfort, practical use, and local retail demand.", "/images/products/1782744308829.jpeg"],
  ["home-textiles", "CYNOVIA Textile Brand Pack", "cynovia-textile-brand-pack", "CYNOVIA textile identity pack for premium home and lifestyle fabric sourcing.", "/images/products/1782967143335.jpeg"],
  ["home-textiles", "CYNOVIA Ginet House Textile", "cynovia-ginet-house-textile", "Soft, breathable textile collection for everyday home and lifestyle comfort.", "/images/products/1782996561119.jpeg"],
  ["gadgets-electronics", "S Younger Lithium Ion Battery", "s-younger-lithium-ion-battery", "Rechargeable lithium-ion battery solution for power backup and electronics use.", "/images/products/1781072560765.jpeg"],
  ["gadgets-electronics", "S Younger 5V Lithium Battery", "s-younger-5v-lithium-battery", "Portable 5V lithium battery package for reliable compact power supply needs.", "/images/products/1781173338447.jpeg"],
  ["gadgets-electronics", "Smart Power Inverter Battery", "smart-power-inverter-battery", "Inverter and battery backup solution for smarter, stable power support.", "/images/products/1781772889561.jpeg"],
  ["gadgets-electronics", "Handheld Portable Turbo Mini Fan", "handheld-portable-turbo-mini-fan", "Type-C USB rechargeable mini fan for travel, desk, and daily cooling.", "/images/products/1783009613418.jpeg"],
  ["medical-supplies-reagents", "BioVision Medical Equipment", "biovision-medical-equipment", "Medical equipment and reagent sourcing support for professional healthcare buyers.", "/images/products/1782717193173.jpeg"],
  ["medical-supplies-reagents", "Auto Optics FA-6500K Analyzer", "auto-optics-fa-6500k-analyzer", "Clinical optics analyzer for diagnostic labs and healthcare procurement requirements.", "/images/products/1783276109216.jpeg"],
  ["gift-corner", "Import and Export Services", "import-export-services", "End-to-end import and export support for sourcing, logistics, and business procurement.", "/images/products/1781838841047.jpeg"],
  ["gift-corner", "China Import Sourcing Service", "china-import-sourcing-service", "China sourcing support for product discovery, supplier coordination, and shipment planning.", "/images/products/1781925833028.jpeg"],
  ["gift-corner", "Air Cargo Import Service", "air-cargo-import-service", "Fast air cargo and import support for urgent commercial product shipments.", "/images/products/1781193311322.jpeg"],
  ["home-appliances", "Commercial File Delivery Machine", "commercial-file-delivery-machine", "Professional equipment package for automated preparation and business service workflows.", "/images/products/1781893911083.jpeg"],
  ["home-appliances", "Small Business Equipment Package", "small-business-equipment-package", "Selected business equipment set for shops, service counters, and growing operations.", "/images/products/1781592153967.jpeg"],
] as const;

export const products: ProductWithCategory[] = productRows.map((row, index) => {
  const category = categories.find((item) => item.slug === row[0]);

  if (!category) {
    throw new Error(`Missing category for ${row[1]}`);
  }

  return {
    id: `${String(index + 1).padStart(8, "0")}-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
    category_id: category.id,
    name: row[1],
    slug: row[2],
    description: row[3],
    image_url: row[4],
    sort_order: index + 1,
    is_featured: index < 8,
    created_at: "2026-06-12T00:00:00.000Z",
    categories: category,
  };
});

export const homeSlides: HomeSlide[] = [
  {
    id: "slide-1",
    title: "CYNOVIA Import and Export Services",
    subtitle: "Global product sourcing, import support, export coordination, and shipment guidance for growing businesses.",
    badge: "Global products. Local confidence.",
    image_url: "/images/slides/import-export-services.jpeg",
    primary_label: "Explore Services",
    primary_href: "/categories",
    secondary_label: "Contact Us",
    secondary_href: "/contact",
    sort_order: 1,
    is_active: true,
    created_at: "2026-06-12T00:00:00.000Z",
  },
  {
    id: "slide-2",
    title: "CYNOVIA Textile Collection",
    subtitle: "Comfortable textile, fashion, and lifestyle product sourcing for local retail and wholesale needs.",
    badge: "Where tradition meets comfort",
    image_url: "/images/slides/cynovia-textile.jpeg",
    primary_label: "View Textiles",
    primary_href: "/categories/home-textiles",
    secondary_label: "Contact Us",
    secondary_href: "/contact",
    sort_order: 2,
    is_active: true,
    created_at: "2026-06-12T00:00:00.000Z",
  },
  {
    id: "slide-3",
    title: "Medical Equipment and Reagents",
    subtitle: "Trusted medical equipment, lab reagent support, and healthcare sourcing from reliable suppliers.",
    badge: "Healthcare sourcing support",
    image_url: "/images/slides/medical-equipment.jpeg",
    primary_label: "View Medical Products",
    primary_href: "/categories/medical-supplies-reagents",
    secondary_label: "Contact Us",
    secondary_href: "/contact",
    sort_order: 3,
    is_active: true,
    created_at: "2026-06-12T00:00:00.000Z",
  },
];
