import type { Category, ProductWithCategory } from "@/lib/types";

export const categories: Category[] = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    name: "Industrial Machinery",
    slug: "industrial-machinery",
    description: "Industrial and commercial machines for production, preparation, and daily business operations.",
    image_url: null,
    sort_order: 1,
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    name: "Food Processing Equipment",
    slug: "food-processing-equipment",
    description: "Commercial food and beverage equipment for cafes, restaurants, and processing lines.",
    image_url: null,
    sort_order: 2,
  },
  {
    id: "33333333-3333-3333-3333-333333333333",
    name: "Medical Supplies & Reagents",
    slug: "medical-supplies-reagents",
    description: "Selected medical supplies, reagents, and healthcare essentials for professional use.",
    image_url: null,
    sort_order: 3,
  },
  {
    id: "44444444-4444-4444-4444-444444444444",
    name: "Printing Supplies",
    slug: "printing-supplies",
    description: "Printer ink, printer heads, and industrial printing supplies.",
    image_url: null,
    sort_order: 4,
  },
  {
    id: "55555555-5555-5555-5555-555555555555",
    name: "Fashion",
    slug: "fashion",
    description: "Everyday apparel, accessories, and textile items for wholesale or retail sourcing.",
    image_url: null,
    sort_order: 5,
  },
  {
    id: "66666666-6666-6666-6666-666666666666",
    name: "Home Textiles",
    slug: "home-textiles",
    description: "Comfortable home textile collections including bedsheets and traditional essentials.",
    image_url: null,
    sort_order: 6,
  },
  {
    id: "77777777-7777-7777-7777-777777777777",
    name: "Home Appliances",
    slug: "home-appliances",
    description: "Reliable home and kitchen appliances for daily household needs.",
    image_url: null,
    sort_order: 7,
  },
  {
    id: "88888888-8888-8888-8888-888888888888",
    name: "Kitchen Accessories",
    slug: "kitchen-accessories",
    description: "Cooking tools, kitchen gadgets, and dining accessories for modern homes and businesses.",
    image_url: null,
    sort_order: 8,
  },
  {
    id: "99999999-9999-9999-9999-999999999999",
    name: "Gadgets & Electronics",
    slug: "gadgets-electronics",
    description: "Mobile accessories, smart gadgets, and practical electronic accessories.",
    image_url: null,
    sort_order: 9,
  },
  {
    id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    name: "Kids Corner",
    slug: "kids-corner",
    description: "Children's clothing, toys, learning products, and baby essentials.",
    image_url: null,
    sort_order: 10,
  },
  {
    id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    name: "Gift Corner",
    slug: "gift-corner",
    description: "Corporate, personalized, and special occasion gifts for every memorable moment.",
    image_url: null,
    sort_order: 11,
  },
];

const productRows = [
  ["industrial-machinery", "Automatic Poultry Feed Making Machine", "automatic-poultry-feed-making-machine", "Automated machinery for producing poultry feed with consistent texture and output."],
  ["industrial-machinery", "Commercial Electric Bitter Machine", "commercial-electric-bitter-machine", "Heavy-duty commercial bitter machine for business-grade food preparation."],
  ["industrial-machinery", "Commercial Oven", "commercial-oven", "Durable commercial oven for bakeries, restaurants, and production kitchens."],
  ["industrial-machinery", "3-Nozzle Soft Ice Cream Making Machine", "3-nozzle-soft-ice-cream-making-machine", "High-capacity soft ice cream machine with three nozzles for flexible serving."],
  ["industrial-machinery", "Commercial Deep Fryer", "commercial-deep-fryer", "Business-ready deep fryer designed for fast and consistent frying output."],
  ["industrial-machinery", "Manual French Fry Slicer", "manual-french-fry-slicer", "Compact slicer for preparing uniform french fries in commercial kitchens."],
  ["food-processing-equipment", "Bubble Tea Equipment (Thailand)", "bubble-tea-equipment-thailand", "Bubble tea equipment sourced for beverage shops and cafe operations."],
  ["food-processing-equipment", "Soft Ice Cream Machines", "soft-ice-cream-machines", "Soft ice cream machines suitable for dessert shops and food counters."],
  ["food-processing-equipment", "Commercial Ovens", "commercial-ovens", "Oven options for food production, bakeries, and restaurants."],
  ["food-processing-equipment", "Deep Fryers", "deep-fryers", "Commercial fryers for snacks, fast food, and restaurant kitchens."],
  ["food-processing-equipment", "French Fry Processing Equipment", "french-fry-processing-equipment", "Processing tools and equipment for preparing french fries at scale."],
  ["printing-supplies", "DDF Printer Ink", "ddf-printer-ink", "Printing ink supply for selected commercial and industrial printer workflows."],
  ["printing-supplies", "Printer Heads", "printer-heads", "Replacement printer heads for maintaining clean and reliable print quality."],
  ["medical-supplies-reagents", "ABLE Dialysis Catheter Kit", "able-dialysis-catheter-kit", "Dialysis catheter kit for medical procurement and healthcare supply inquiries."],
  ["fashion", "Men's Clothing", "mens-clothing", "Men's clothing options for sourcing, retail, and business supply needs."],
  ["fashion", "Men's Premium Shirt", "mens-premium-shirt", "Premium men's shirt suitable for retail, corporate wear, and fashion sourcing."],
  ["fashion", "Lungi", "lungi", "Traditional lungi options for everyday wear and retail collections."],
  ["fashion", "Women's Clothing", "womens-clothing", "Women's apparel selections for retail and sourcing requirements."],
  ["fashion", "Fashion Accessories", "fashion-accessories", "Accessories to complement apparel collections and lifestyle retail."],
  ["fashion", "Gamcha / Gamsa", "gamcha-gamsa", "Traditional gamcha or gamsa textile products for everyday utility."],
  ["home-textiles", "Bedsheets", "bedsheets", "Comfortable bedsheet collections for home textile sourcing."],
  ["home-textiles", "Gamcha / Gamsa", "home-textile-gamcha-gamsa", "Soft traditional textile products for home and daily use."],
  ["home-appliances", "Kitchen Appliances", "kitchen-appliances", "Useful kitchen appliances for everyday household and business needs."],
  ["home-appliances", "Household Appliances", "household-appliances", "Reliable appliances for domestic and commercial household requirements."],
  ["home-appliances", "Small Electronics", "small-electronics", "Compact electronics for home, office, and practical daily use."],
  ["kitchen-accessories", "Kitchen Accessories", "kitchen-accessories-product", "Everyday kitchen accessories for cooking, storage, and serving."],
  ["kitchen-accessories", "Cooking Tools", "cooking-tools", "Practical cooking tools for home kitchens and food businesses."],
  ["kitchen-accessories", "Kitchen Gadgets", "kitchen-gadgets", "Convenient kitchen gadgets that simplify preparation and serving."],
  ["gadgets-electronics", "Mobile Accessories", "mobile-accessories", "Mobile accessories for everyday connectivity, charging, and protection."],
  ["gadgets-electronics", "Smart Gadgets", "smart-gadgets", "Smart gadgets for modern work, travel, and lifestyle needs."],
  ["gadgets-electronics", "Electronic Accessories", "electronic-accessories", "Useful electronic accessories for homes, offices, and retail supply."],
  ["kids-corner", "Children's Clothing", "childrens-clothing", "Comfortable clothing selections for children and retail buyers."],
  ["kids-corner", "Toys & Learning Products", "toys-learning-products", "Toys and learning products designed for play, development, and discovery."],
  ["kids-corner", "Baby Essentials", "baby-essentials", "Everyday baby essentials for families and childcare sourcing."],
  ["gift-corner", "Corporate Gifts", "corporate-gifts", "Professional gift options for teams, clients, and corporate events."],
  ["gift-corner", "Corporate Gift Set", "corporate-gift-set", "Curated corporate gift set for clients, events, and professional occasions."],
  ["gift-corner", "Personalized Gifts", "personalized-gifts", "Customizable gift options for personal and business occasions."],
  ["gift-corner", "Special Occasion Gifts", "special-occasion-gifts", "Gift selections for celebrations, milestones, and seasonal events."],
  ["gift-corner", "Home Decor Gift", "home-decor-gift", "Decorative home gift items for warm and thoughtful presentation."],
] as const;

export const products: ProductWithCategory[] = productRows.map((row, index) => {
  const category = categories.find((item) => item.slug === row[0]);

  if (!category) {
    throw new Error(`Missing category for ${row[1]}`);
  }

  return {
    id: `${String(index + 1).padStart(8, "0")}-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
    category_id: category.id,
    name: row[1],
    slug: row[2],
    description: row[3],
    image_url: null,
    is_featured: index < 8,
    created_at: "2026-06-12T00:00:00.000Z",
    categories: category,
  };
});
